interface_type: anthropic
model: anthropic.claude-3-5-sonnet-20241022-v2:0
prompt_mode: default
prompt_type: default
num_incontext_examples: -1
temperature: 0.0
aws_region: us-west-2
access_key_env_var: AWS_ACCESS_KEY
secret_key_env_var: AWS_SECRET_KEY
debug: True
