interface_type: openai
model: gpt-4.1-nano-2025-04-14
prompt_mode: default
prompt_type: default
num_incontext_examples: -1
temperature: 0.0
api_timeout: 120.0
seed: 100
api_key_env_var: OPENAI_API_KEY
debug: True
